"""The recorder: a discovery event log -> a ``Capability`` -> a YAML file. Pure, no browser."""

from cua.discovery.recorder.build import (
    build_capability,
    check_savable,
    output,
    step_inputs,
    target,
    to_step,
    used_inputs,
)
from cua.discovery.recorder.checkpoint import checkpoint
from cua.discovery.recorder.events import (
    FIELD_GAP,
    FIELD_TOOLS,
    LOGOUT_WORDS,
    READ_TOOLS,
    STEP_TOOLS,
    NotSaved,
    field_area,
    flag_leaks,
    goes_to_a_page,
    input_name,
    is_select,
    mark_submits,
    needed_moves,
    no_op,
    one_read_per_table,
    same_click,
    same_spot,
    step_events,
    without_detours,
    without_logout,
    without_no_ops,
)
from cua.discovery.recorder.save import crops_for, describe, save_artifact
from cua.discovery.recorder.types import input_types, pick_type, shapes_of

__all__ = [
    "NotSaved",
    "check_savable",
    "FIELD_GAP",
    "FIELD_TOOLS",
    "LOGOUT_WORDS",
    "READ_TOOLS",
    "STEP_TOOLS",
    "build_capability",
    "checkpoint",
    "crops_for",
    "describe",
    "field_area",
    "flag_leaks",
    "goes_to_a_page",
    "input_types",
    "input_name",
    "is_select",
    "mark_submits",
    "needed_moves",
    "no_op",
    "one_read_per_table",
    "output",
    "pick_type",
    "same_click",
    "same_spot",
    "save_artifact",
    "shapes_of",
    "step_events",
    "step_inputs",
    "target",
    "to_step",
    "used_inputs",
    "without_detours",
    "without_logout",
    "without_no_ops",
]
